# .github/workflows/theme-check.yml
name: Theme Check
on: [push]
jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.' # optional, could be './dist'
          token: ${{ github.token }}
          base: main
extends: :theme_app_extension
root: .
extends_core: true

MatchingTranslations:
  enabled: true
  ignore_missing: true
  ignore_unused: true
  ignore_missing_default_locale: true
  ignore_missing_template: true
  ignore_missing_section: true
  ignore_missing_snippet: true
  ignore_missing_asset: true