name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@v1
        with:
          store: ${{ secrets.SHOP_STORE }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          collection_handle: all
          pull_theme: "124781560000"
          lhci_min_score_performance: 0.6
          lhci_min_score_accessibility: 0.9
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: .
          token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          base: main
          flags: --config .theme-check.yml
